version: "2"

services:

  server:
    image: localhost:5000/sut
    build:
      context: .
      dockerfile: Dockerfile
    command: -v -v

  version:
    image: localhost:5000/sut
    build:
      context: .
      dockerfile: Dockerfile
    command: -V

  sut:
    image: alpine:3.17
    depends_on:
      - server
      - version
    entrypoint: ""
    command: >-
      /bin/sh -c '
      apk add --no-cache bind-tools &&
      dig @server dnssec.works +dnssec +multi | tee /dev/stderr | grep -wq NOERROR &&
      dig @server fail01.dnssec.works +dnssec +multi +time=120 | tee /dev/stderr | grep -wq SERVFAIL &&
      dig @server fail02.dnssec.works +dnssec +multi +time=120 | tee /dev/stderr | grep -wq SERVFAIL &&
      dig @server fail03.dnssec.works +dnssec +multi +time=120 | tee /dev/stderr | grep -wq SERVFAIL &&
      dig @server fail04.dnssec.works +dnssec +multi +time=120 | tee /dev/stderr | grep -wq SERVFAIL
      '
