name: ci

on:
  pull_request:
    branches:
      - "main"
      - "master"
  push:
    branches:
      - "main"
      - "master"

jobs:

  docker:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      cache_from: |
        docker.io/klutchell/unbound:main
        ghcr.io/klutchell/unbound:main
        docker.io/klutchell/unbound:latest
        ghcr.io/klutchell/unbound:latest
      images: |
        docker.io/klutchell/unbound
        ghcr.io/klutchell/unbound
      platforms: |
        linux/amd64
        linux/arm64
        linux/arm/v7
        linux/arm/v6
      dockerhub_description_repo: klutchell/unbound
