name: CI

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "main"
      - "master"
  push:
    tags:
      - v*.*.*

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@master
    secrets:
      FLOWZONE_TOKEN: ${{ secrets.FLOWZONE_TOKEN }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
      DOCKER_REGISTRY_PASS: ${{ secrets.DOCKER_REGISTRY_PASS }}
    with:
      protect_branch: false
      docker_platforms: |
        linux/amd64
        linux/arm64
        linux/arm/v7
        linux/arm/v6
      dockerhub_repo: klutchell/unbound
      ghcr_repo: klutchell/unbound
      docker_cache_from: |
        docker.io/klutchell/unbound:main
        ghcr.io/klutchell/unbound:main
        docker.io/klutchell/unbound:latest
        ghcr.io/klutchell/unbound:latest
